- name: "Application: {{ application }} ==> Instance: {{ tomcat_instances[application].instance_name }}"
  tags: [ never, instances ]
  debug:
    msg: "Instance: {{ tomcat_instances[application].instance_name }}"

- name: mkdir under "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}"
  tags: [ never, instances ]
  file:
    path:  "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}/{{ item }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_items:
    - "conf"
    - "temp"
    - "webapps"
    - "work"

- name: mkdir /var/log/tomcats/{{ tomcat_instances[application].instance_name }}
  tags: [ never, instances ]
  file:
    path:  "/var/log/tomcats/{{ tomcat_instances[application].instance_name }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Copy default conf files from catalina_home
  tags: [ never, instances ]
  copy:
    remote_src: yes
    src:   "{{ tomcat_install_dir }}/{{ tomcat_symlink }}/conf/{{ item }}"
    dest:  "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}/conf/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  with_items: "{{ tomcat_necessary_default_conf_files }}"

- name: "(For DEMO) Copy sample application 'ROOT' from catalina_home"
  tags: [ never, instances ]
  copy:
    remote_src: yes
    src:   "{{ tomcat_install_dir }}/{{ tomcat_symlink }}/webapps/ROOT"
    dest:  "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}/webapps/"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Update logging.properties
  tags: [ never, instances ]
  template:
    src:  "logging-properties.j2"
    dest: "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}/conf/logging.properties"

- name: Update server.xml
  tags: [ never, instances ]
  template:
    src:  "{{ template_server_xml }}"
    dest: "{{ tomcat_instances_dir }}/{{ tomcat_instances[application].instance_name }}/conf/server.xml"

- name: Update service setting
  tags: [ never, instances ]
  template:
    src: "instance-service.j2"
    dest: /usr/lib/systemd/system/tomcat-{{ tomcat_instances[application].instance_name }}.service

- name: systemd daemon_reload
  tags: [ never, instances ]
  systemd:
    name: "tomcat-{{ tomcat_instances[application].instance_name }}"
    daemon_reload: yes

# - name: Enable tomcat service on startup
#   systemd:
#     name: "tomcat-{{ application }}-{{ tomcat_instances[application].instance_name }}"
#     enabled: yes
#     daemon_reload: yes
