version: '3.7'

services:
  control:
    image: ansible_controller
    container_name: ansible
    working_dir: "/home/ansible"
    volumes:
      - /c/Users/Public/repos/ansible:/home/ansible/code
      - /c/Users/Public/repos/jenkins:/home/ansible/jenkins
      - /c/Users/Public/docker-shared/downloads:/home/ansible/downloads
      - /c/Users/Public/docker-shared:/tmp/shared
    tty: true

  jenkins:
    image: centos/systemd
    container_name: jk
    working_dir: "/var/lib"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /c/Users/Public/docker-shared/downloads/jenkins-2.204.5:/var/tmp/downloads/jenkins-2.204.5
      - /c/Users/Public/docker-shared/data-jenkins-plugins:/var/lib/jenkins_plugins
    ports:
      - "8083:8080"
    privileged: true

  app:
    image: ymktk/centos-systemd:tomcat-9.0
    container_name: app
    working_dir: "/var/lib/tomcats"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /c/Users/Public/docker-shared/downloads:/var/tmp/downloads
    ports:
      - "8091:8091"
      - "8092:8092"
    privileged: true
