galaxy_info:
  role_name: java
  author: Takahiro Yamaki
  description: Java for CentOS
  company: Weekend Developer
  license: license (Apache-2.0)
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags:
    - java
    - jdk

dependencies: []
