- name: Create symlink {{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }} to {{ tomcat_install_path }}/{{ tomcat_service_name }}
  file:
    src:  "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ tomcat_install_path }}/{{ tomcat_service_name }}"
    state: link

- name: Delete Tomcat default webapps ("{{ tomcat_unnecessary_default_apps }}")
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/webapps/{{ item }}"
    state: absent
  with_items: "{{ tomcat_unnecessary_default_apps }}"

- name: Set recursively webapps directory owner/group for production installation
  file:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/webapps"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Create tomcat PID directory ("{{ tomcat_pid_dir }}")
  file:
    path: '{{ tomcat_pid_dir }}'
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0750

- name: Create tomcat instances directory ("{{ tomcat_instances_dir }}")
  file:
    path: '{{ tomcat_instances_dir }}'
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Configure each instance
  include_tasks: settings-instance.yml
  with_items: "{{ tomcat_instances }}"
  loop_control:
    loop_var: application
