---
- name: "groupadd {{ jenkins_group }}"
  group:
    name: "{{ jenkins_group }}"
    gid:  "{{ jenkins_group_gid | default(omit) }}"
    state: present

- name: "useradd {{ jenkins_user }}"
  user:
    name:  "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    uid:   "{{ jenkins_user_uid | default(omit) }}"
    state: present

# Service user permission
- name: usermod -aG docker {{ jenkins_user }}
  user:
    name: "{{ jenkins_user }}"
    groups:
      - "docker"
    append: yes

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - curl
      - git
      # - libselinux-python
      # - initscripts
    state: present

- name: "Ensure necessary dirs"
  file:
    path:  "{{ item }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  with_items:
    - "{{ app_mount_point }}"

# - name: Stop and disable firewalld
#   service:
#     name:    firewalld
#     state:   stopped
#     enabled: no
