- name: "mkdir {{ jenkins_download_dir }}/jenkins-{{ jenkins_version }}"
  file:
    path:  "{{ jenkins_download_dir }}/jenkins-{{ jenkins_version }}"
    state: directory

- name: "Download jenkins.war ver.{{ jenkins_version }}"
  get_url:
    url:       "{{ jenkins_download_URL }}/{{ jenkins_version }}/jenkins.war"
    dest:      "{{ jenkins_download_dir }}/jenkins-{{ jenkins_version }}/jenkins.war"
    sha256sum: "{{ jenkins_war_sha256 }}"
    timeout: 120
